make_php

diff --git a/misc/make_php b/misc/make_php
--- a/misc/make_php
+++ b/misc/make_php
@@ -4,9 +4,14 @@ function install_php() {
 	
 	pushd ${OPENSHIFT_DIY_DIR}
 	rm -f php-${DIST_PHP_VER}.tar.gz
-	wget http://php.net/distributions/php-${DIST_PHP_VER}.tar.gz
-	tar -zxf php-${DIST_PHP_VER}.tar.gz
-	rm -f php-${DIST_PHP_VER}.tar.gz
+	echo "Downloading PHP source code"
+        wget -nv http://php.net/distributions/php-${DIST_PHP_VER}.tar.gz && \
+        tar -zxf php-${DIST_PHP_VER}.tar.gz                              && \
+        rm -f php-${DIST_PHP_VER}.tar.gz
+    if [ $? != 0 ]; then
+        echo "ERROR! CANNOT DOWNLOAD php-${DIST_PHP_VER}"
+        return 1
+    fi
 	pushd php-${DIST_PHP_VER}
 	
 	mkdir -p ${LIB_DIR}
@@ -53,7 +58,7 @@ function install_php() {
             --enable-sysvshm \
             --enable-sysvmsg \
             --enable-opcache
-	make
+	make -j4
 	make install
 	
 	popd
@@ -62,10 +67,10 @@ function install_php() {
 }
 
 function check_php() {
-	if [[ -x $OPENSHIFT_RUNTIME_DIR/bin/php-cgi ]] ; then
-	if [[ "`$OPENSHIFT_RUNTIME_DIR/bin/php-cgi`" =~ "${DIST_PHP_VER}" ]] ; then
+	if [[ -x $OPENSHIFT_RUNTIME_DIR/bin/php-cgi ]] && \
+       [[ "`$OPENSHIFT_RUNTIME_DIR/bin/php-cgi`" =~ "${DIST_PHP_VER}" ]] 
+    then
 		return 0
-	fi
 	fi
 	
 	echo "Check PHP ${DIST_PHP_VER} Failed. Start installing"
